POLLS_TESTING_SEED= 243457283
AUTHOR_ID = KPRCA
SERVICE_ID = 00035
CFLAGS = -O0 -Werror -Wall -Wno-unused-function -Wno-unused -Wno-compare-distinct-pointer-types -Wno-sometimes-uninitialized
POLLS_RELEASE_SEED = -868333550

ifndef ROOT_DIR
	ROOT_DIR=..
endif

include $(ROOT_DIR)/cgc-cb.mk
