POLLS_RELEASE_SEED= 1855385651
POLLS_TESTING_SEED= 2126893025
AUTHOR_ID  = CROMU
SERVICE_ID = 00020
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed
NO_STRIP   = 1

ifndef ROOT_DIR
	ROOT_DIR=..
endif

include $(ROOT_DIR)/cgc-cb.mk
