POLLS_RELEASE_SEED= 2123542660
POLLS_TESTING_SEED= 1934104925
AUTHOR_ID  = NRFIN
SERVICE_ID = 00023
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed

ifndef ROOT_DIR
	ROOT_DIR=..
endif

include $(ROOT_DIR)/cgc-cb.mk
