POLLS_RELEASE_SEED= 286462723
POLLS_TESTING_SEED= 104578085
AUTHOR_ID  = CROMU
SERVICE_ID = 00014
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed
ifndef ROOT_DIR
	ROOT_DIR=..
endif

include $(ROOT_DIR)/cgc-cb.mk
