POLLS_TESTING_SEED= -1707631914
AUTHOR_ID  = KPRCA
SERVICE_ID = 00012
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed
POLLS_RELEASE_SEED = -1791831965

ifndef ROOT_DIR
	ROOT_DIR=..
endif

include $(ROOT_DIR)/cgc-cb.mk
