POLLS_RELEASE_SEED= 1821875187
POLLS_TESTING_SEED= 2037864129
AUTHOR_ID  = CROMU
SERVICE_ID = 00044
POLLS_TESTING_COUNT = 1000

CXXFLAGS    = -fno-exceptions -fno-rtti
CFLAGS      = -O0 -g -fno-exceptions -fno-rtti

ifndef ROOT_DIR
	ROOT_DIR=..
endif

include $(ROOT_DIR)/cgc-cb.mk
