POLLS_TESTING_SEED= -1838430804
AUTHOR_ID  = KPRCA
SERVICE_ID = 00021
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed -Wall -Wno-unused-variable -Wno-unused-function
POLLS_RELEASE_SEED = 952316475

ifndef ROOT_DIR
	ROOT_DIR=..
endif

include $(ROOT_DIR)/cgc-cb.mk
