POLLS_RELEASE_SEED= -771117232
POLLS_TESTING_SEED= 1687964335
AUTHOR_ID  = CROMU
SERVICE_ID = 00026
POLLS_TESTING_COUNT = 1000

CXXFLAGS    = -g -fno-exceptions -fno-rtti
CFLAGS      = -g -fno-exceptions -fno-rtti

ifndef ROOT_DIR
	ROOT_DIR=..
endif

include $(ROOT_DIR)/cgc-cb.mk
