AUTHOR_ID  = KPRCA
SERVICE_ID = 00087
CFLAGS     = -O3 -g -Werror -Wno-overlength-strings -Wno-packed -include src/_defines.h
VULN_COUNT = 1


ifndef ROOT_DIR
	ROOT_DIR=..
endif

include $(ROOT_DIR)/cgc-cb.mk
