POLLS_RELEASE_SEED= 377587857
POLLS_TESTING_SEED= -591896626
AUTHOR_ID  = CROMU
SERVICE_ID = 00038
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed
ifndef ROOT_DIR
	ROOT_DIR=..
endif

include $(ROOT_DIR)/cgc-cb.mk
