POLLS_RELEASE_SEED= 646035515
POLLS_TESTING_SEED= -245294859
AUTHOR_ID  = CROMU
SERVICE_ID = 00039
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed

ifndef ROOT_DIR
	ROOT_DIR=..
endif

include $(ROOT_DIR)/cgc-cb.mk
