POLLS_RELEASE_SEED= -2102435796
POLLS_TESTING_SEED= 1163751197
AUTHOR_ID  = CROMU
SERVICE_ID = 00011
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed

ifndef ROOT_DIR
	ROOT_DIR=..
endif

include $(ROOT_DIR)/cgc-cb.mk
