AUTHOR_ID  = LUNGE
SERVICE_ID = 00005
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed -Wunused
NO_STRIP = 1 

POLLS_RELEASE_SEED=0
POLLS_TESTING_SEED=0

ifndef ROOT_DIR
	ROOT_DIR=..
endif

include $(ROOT_DIR)/cgc-cb.mk
