POLLS_RELEASE_SEED= 636469518
POLLS_TESTING_SEED= 2123284952
AUTHOR_ID  = CROMU
SERVICE_ID = 00042
POLLS_TESTING_COUNT = 1000
NO_STRIP=1

CXXFLAGS    = -fno-exceptions -fno-rtti
CFLAGS      = -O0 -g -fno-exceptions -fno-rtti

ifndef ROOT_DIR
	ROOT_DIR=..
endif

include $(ROOT_DIR)/cgc-cb.mk
