POLLS_TESTING_SEED= 652665024
AUTHOR_ID  = KPRCA
SERVICE_ID = 00009
POLLS_RELEASE_SEED = -805564115
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed

include /usr/share/cb-testing/cgc-cb.mk
