AUTHOR_ID  = KPRCA
SERVICE_ID = 00062
CFLAGS     = -O0 -g -Wno-overlength-strings -Wno-packed -Wall -Wno-typedef-redefinition -Wno-unused-function -Wno-unused-variable -Werror
VULN_COUNT = 1

ifndef ROOT_DIR
	ROOT_DIR=..
endif

include $(ROOT_DIR)/cgc-cb.mk
