POLLS_RELEASE_SEED= 1329292553
POLLS_TESTING_SEED= -1639508102
AUTHOR_ID  = CROMU
SERVICE_ID = 00028
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed -fblocks

ifndef ROOT_DIR
	ROOT_DIR=..
endif

include $(ROOT_DIR)/cgc-cb.mk
