POLLS_RELEASE_SEED= 385827619
AUTHOR_ID  = KPRCA
SERVICE_ID = 00050
CFLAGS     = -O3 -g -Werror -Wno-overlength-strings -Wno-packed -Wall -Wno-unused-function -Wno-unused-variable
POLLS_TESTING_COUNT = 1000
POLLS_TESTING_SEED = -2091984071

ifndef ROOT_DIR
	ROOT_DIR=..
endif

include $(ROOT_DIR)/cgc-cb.mk
