POLLS_RELEASE_SEED= 1394381733
POLLS_TESTING_SEED= 733675487
AUTHOR_ID  = NRFIN
SERVICE_ID = 00006
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed

ifndef ROOT_DIR
	ROOT_DIR=..
endif

include $(ROOT_DIR)/cgc-cb.mk
