POLLS_RELEASE_SEED= 172223516
POLLS_TESTING_SEED= -750311787
AUTHOR_ID  = NRFIN
SERVICE_ID = 00030
CFLAGS     = -O0 -g -Wno-overlength-strings -Wno-packed

ifndef ROOT_DIR
	ROOT_DIR=..
endif

include $(ROOT_DIR)/cgc-cb.mk
