AUTHOR_ID  = CROMU
SERVICE_ID = 00070
VULN_COUNT = 2

CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed
CXXFLAGS   = -fno-exceptions -fno-rtti

ifndef ROOT_DIR
	ROOT_DIR=..
endif

include $(ROOT_DIR)/cgc-cb.mk
