POLLS_TESTING_SEED= -1974231999
AUTHOR_ID   = KPRCA
SERVICE_ID  = 00020
CFLAGS      = -g -Werror -Wno-overlength-strings -Wno-packed
POLLS_RELEASE_SEED = -423157946

ifndef ROOT_DIR
	ROOT_DIR=..
endif

include $(ROOT_DIR)/cgc-cb.mk
