POLLS_RELEASE_SEED= -1355571314
POLLS_TESTING_SEED= -1322933234
AUTHOR_ID  = CROMU
SERVICE_ID = 00033
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed

ifndef ROOT_DIR
	ROOT_DIR=..
endif

include $(ROOT_DIR)/cgc-cb.mk
