POLLS_TESTING_SEED= 346988430
AUTHOR_ID  = KPRCA
SERVICE_ID = 00042
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed
POLLS_RELEASE_SEED = 140296829

ifndef ROOT_DIR
	ROOT_DIR=..
endif

include $(ROOT_DIR)/cgc-cb.mk
