POLLS_TESTING_SEED= -881362031
AUTHOR_ID  = KPRCA
SERVICE_ID = 00002
CFLAGS     = -Os -g -Werror -Wno-overlength-strings -Wno-packed

POLLS_RELEASE_SEED = 2542617775

ifndef ROOT_DIR
	ROOT_DIR=..
endif

include $(ROOT_DIR)/cgc-cb.mk
