POLLS_RELEASE_SEED= -990494923
POLLS_TESTING_SEED= -1708909191
AUTHOR_ID  = NRFIN
SERVICE_ID = 00041
CFLAGS     = -O0 -g -Wno-overlength-strings -Wno-packed

ifndef ROOT_DIR
	ROOT_DIR=..
endif

include $(ROOT_DIR)/cgc-cb.mk
