POLLS_RELEASE_SEED= -496314762
POLLS_TESTING_SEED= -1397003294
AUTHOR_ID  = NRFIN
SERVICE_ID = 00018
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed

ifndef ROOT_DIR
	ROOT_DIR=..
endif

include $(ROOT_DIR)/cgc-cb.mk
