POLLS_RELEASE_SEED= -175986316
POLLS_TESTING_SEED= -560649487
AUTHOR_ID  = CROMU
SERVICE_ID = 00021
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed

ifndef ROOT_DIR
	ROOT_DIR=..
endif

include $(ROOT_DIR)/cgc-cb.mk
