AUTHOR_ID  = CROMU
SERVICE_ID = 00012
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed
NO_STRIP = 1
POLLS_RELEASE_SEED=388550987
POLLS_TESTING_SEED=-803034210

ifndef ROOT_DIR
	ROOT_DIR=..
endif

include $(ROOT_DIR)/cgc-cb.mk
