POLLS_RELEASE_SEED= -137778333
POLLS_TESTING_SEED= 1832052317
AUTHOR_ID  = CROMU
SERVICE_ID = 00043
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed

ifndef ROOT_DIR
	ROOT_DIR=..
endif

include $(ROOT_DIR)/cgc-cb.mk
