POLLS_RELEASE_SEED= 128230504
POLLS_TESTING_SEED= -135449884
AUTHOR_ID  = CROMU
SERVICE_ID = 00032
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed

ifndef ROOT_DIR
	ROOT_DIR=..
endif

include $(ROOT_DIR)/cgc-cb.mk
