POLLS_RELEASE_SEED= -1197662839
POLLS_TESTING_SEED= -2119542976
AUTHOR_ID  = CROMU
SERVICE_ID = 00025
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed

ifndef ROOT_DIR
	ROOT_DIR=..
endif

include $(ROOT_DIR)/cgc-cb.mk
