POLLS_RELEASE_SEED= -1019954525
POLLS_TESTING_SEED= 1886635574
AUTHOR_ID  = CROMU
SERVICE_ID = 00002
CFLAGS     = -O0 -g -Wall -Werror -Wno-overlength-strings -Wno-packed -mfpmath=sse -msse2

ifndef ROOT_DIR
	ROOT_DIR=..
endif

include $(ROOT_DIR)/cgc-cb.mk
