POLLS_RELEASE_SEED= 1198392638
AUTHOR_ID  = KPRCA
SERVICE_ID = 00024
CFLAGS     = -O3 -g -Wno-overlength-strings -Wno-packed -DDB_CURRENT -fno-strict-aliasing
POLLS_TESTING_SEED = 1804088789

ifndef ROOT_DIR
	ROOT_DIR=..
endif

include $(ROOT_DIR)/cgc-cb.mk
