AUTHOR_ID  = KPRCA
SERVICE_ID = 00088
CFLAGS     = -O2 -g -Wno-overlength-strings -Wno-packed -Wall -Werror 
CXXFLAGS   = --std=c++11 -fno-exceptions -fno-rtti -DCPLUSPLUS -Dmain=_main
VULN_COUNT = 1
POLLS_RELEASE_MAX_DEPTH=1024

ifndef ROOT_DIR
	ROOT_DIR=..
endif

include $(ROOT_DIR)/cgc-cb.mk
