POLLS_TESTING_SEED= 1640503667
AUTHOR_ID  = KPRCA
SERVICE_ID = 00017
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed
POLLS_RELEASE_SEED = -236520787

ifndef ROOT_DIR
	ROOT_DIR=..
endif

include $(ROOT_DIR)/cgc-cb.mk
