POLLS_RELEASE_SEED= 2067699275
POLLS_TESTING_SEED= -209775003
AUTHOR_ID  = CROMU
SERVICE_ID = 00003
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed

ifndef ROOT_DIR
	ROOT_DIR=..
endif

include $(ROOT_DIR)/cgc-cb.mk
