AUTHOR_ID  = KPRCA
SERVICE_ID = 00086
CFLAGS     = -O1 -g -Werror -Wno-overlength-strings -Wno-packed -Wall -mstackrealign -DDISABLE_HEAP_GUARD -include src/_defines.h
VULN_COUNT = 1

ifndef ROOT_DIR
	ROOT_DIR=..
endif

include $(ROOT_DIR)/cgc-cb.mk
