POLLS_RELEASE_SEED= 1139762139
POLLS_TESTING_SEED= 266103236
AUTHOR_ID  = CROMU
SERVICE_ID = 00004
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed

ifndef ROOT_DIR
	ROOT_DIR=..
endif

include $(ROOT_DIR)/cgc-cb.mk
