AUTHOR_ID  = NRFIN
SERVICE_ID = 00045
CFLAGS     = -O0 -g -Wno-overlength-strings -Wno-packed
VULN_COUNT = 1
POLLS_RELEASE_MAX_DEPTH = 500

ifndef ROOT_DIR
	ROOT_DIR=..
endif

include $(ROOT_DIR)/cgc-cb.mk
