AUTHOR_ID  = CROMU
SERVICE_ID = 00065
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed -DENABLE_BUFFERED_PRINTF
VULN_COUNT = 1
ifndef ROOT_DIR
	ROOT_DIR=..
endif

include $(ROOT_DIR)/cgc-cb.mk
