AUTHOR_ID  = CROMU
SERVICE_ID = 00015
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed

POLLS_RELEASE_SEED=594936938
POLLS_TESTING_SEED=-1420921681

ifndef ROOT_DIR
	ROOT_DIR=..
endif

include $(ROOT_DIR)/cgc-cb.mk
