POLLS_RELEASE_SEED= 14079784
POLLS_TESTING_SEED= -1469926562
AUTHOR_ID  = CROMU
SERVICE_ID = 00016
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed

ifndef ROOT_DIR
	ROOT_DIR=..
endif

include $(ROOT_DIR)/cgc-cb.mk
