POLLS_RELEASE_SEED= 2130245018
POLLS_TESTING_SEED= 1738410521
AUTHOR_ID  = CROMU
SERVICE_ID = 00008

CFLAGS      = -O0 -g -Werror -Wno-overlength-strings -Wno-packed

ifndef ROOT_DIR
	ROOT_DIR=..
endif

include $(ROOT_DIR)/cgc-cb.mk
