POLLS_RELEASE_SEED= -335562927
POLLS_TESTING_SEED= 1561654603
AUTHOR_ID  = NRFIN
SERVICE_ID = 00007
POLLS_RELEASE_COUNT = 1000

CFLAGS = -Wno-overlength-strings -Wno-packed -Wno-trigraphs -g

ifndef ROOT_DIR
	ROOT_DIR=..
endif

include $(ROOT_DIR)/cgc-cb.mk

