POLLS_RELEASE_SEED= 1578966870
POLLS_TESTING_SEED= -1104170671
AUTHOR_ID  = NRFIN
SERVICE_ID = 00035
CFLAGS     = -O0 -g -Wno-overlength-strings -Wno-packed

ifndef ROOT_DIR
	ROOT_DIR=..
endif

include $(ROOT_DIR)/cgc-cb.mk
